version: 2

project_name: cmd-store

before:
  hooks:
    - go mod tidy
    - go generate ./...


builds:
  - id: cmd-store
    main: ./cmd/cli/
    binary: cmd-store
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - >
        -s -w
        -X main.Version={{ .Env.Version }}
        -X main.Commit={{ .Env.Commit }}
        -X main.Date={{ .Env.Date }}
    env:
      - CGO_ENABLED=0

archives:
  - id: cmd-store
    builds:
    - cmd-store
    format: tar.gz
    name_template: >-
      cmd_store_{{- .Os }}_{{- .Arch }}
    format_overrides:
      - goos: windows
        format: zip

