version: 2

project_name: cmd-store

before:
  hooks:
    - go mod tidy
    - go generate ./...


builds:
  - id: cmd-store
    main: ./cmd/store/main.go
    binary: cmd-store
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - >
        "-s -w -X github.com/ezratameno/cmd-store/cmd/cli.version={{ .Env.Version }} -X github.com/ezratameno/cmd-store/cmd/cli.commit={{ .Env.Commit }} -X github.com/ezratameno/cmd-store/cmd/cli.date={{ .Env.Date }}"
    env:
      - CGO_ENABLED=0

archives:
  - id: cmd-store
    builds:
    - cmd-store
    format: tar.gz
    name_template: >-
      cmd_store_{{- .OS} }}_{{- .Arch }}
    format_overrides:
      - goos: windows
        format: zip

