name: CI

permissions:
  contents: write

on:
  pull_request:
    

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24.0

      - name: Bump version and push tag
        uses: mathieudutour/github-tag-action@v6.2
        id: tag_version
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: main

      - name: Checkoout to the tag
        run: |
          git fetch --tags
          git checkout ${{ steps.tag_version.outputs.new_tag }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          Version: ${{ steps.tag_version.outputs.new_tag }}
          Commit: ${{ github.sha }}
          Date: ${{ github.event.pull_request.merged_at || github.event.pull_request.updated_at || github.event.pull_request.created_at }}